api_platform:
    title: Smart Café API
    description: API pour le Smart Café - Application de gestion et prise de commandes
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
        swagger_ui_extra_configuration:
            tryItOutEnabled: true
            filter: true
            deepLinking: true
            displayRequestDuration: true
            docExpansion: list
            showExtensions: true
            showCommonExtensions: true
            defaultModelsExpandDepth: 2
            defaultModelExpandDepth: 2
            syntaxHighlight.theme: monokai
